### PR TITLE
Ensure type consistency on filter stream's matching rule ID

### PR DESCRIPTION
**Pull request by rMaxiQp**
A proposal of making sure filer stream's matching rule has a consistent type.

### CODE REVIEW

**Comment by rMaxiQp** [comment]
I have read and agree to the Twitter Developer Agreement and Policy

**Comment by rMaxiQp** [comment]
recheck

**Comment by igorbrigadir** [comment]
yes! I also think making it `"id": "1436114489988968481",` makes most sense, as opposed to `id_str`

**Comment by rMaxiQp** [comment]
Agree that making `id` string would be the cleanest solution here. 

I'm providing two possible solutions as options, happy to take the suggestion and making the type conversion as the only way to go here as well.

**Comment by igorbrigadir** [comment]
Looks like there's a change already? https://twittercommunity.com/t/filtered-stream-matching-rules-id-is-now-a-string/159527

**Comment by rMaxiQp** [comment]
Thanks for the update there. Closing the PR since it's already applied here. 🙏

**Comment by igorbrigadir** [comment]
Well - i don't know about closing the PR - maybe it's good to reopen it so it can be merged properly and at least it would be easier to see what changed - but i'm not twitter and i don't know how strictly they want to manage this repo - so..
 ¯\\_(ツ)_/¯

**Comment by iamdaniele** [comment]
Thanks all for the discussion. @rMaxiQp we have two options:

1. You can amend your proposal's status to Withdrawn. This indicates you no longer need to submit the proposal at this time; you can also submit another proposal, including a revised version of this proposal, at any time.
2. We can change the status of the proposal to Superseded. This indicates that a solution was already implemented in the platform to fulfill the functionality described by your proposal.

In either case your proposal is still archived and can be referenced in future evaluations.

Let us know which option you prefer. If we don't hear from you, we'll mark the proposal as Superseded.

**Comment by rMaxiQp** [comment]
I think the second option works for me here. Thank you for the update here.

**Pull request merged**
