### PR TITLE
Create 000-retweets.md

### PR DESCRIPTION
**Pull request by igorbrigadir**
Add a proposal to modify the retweets API https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference/get-tweets-id-retweeted_by

### CODE REVIEW

**Comment by igorbrigadir** [comment]
I have read and agree to the Twitter Developer Agreement and Policy

**Comment by igorbrigadir** [comment]
recheck

**Comment by igorbrigadir** [comment]
Any response to this or any of the other proposals?

**Comment by bhalsey** [comment]
Thank you for your contribution!  Our engineering team is reviewing your proposal and will provide feedback in a couple weeks.

**Comment by igorbrigadir** [comment]
Thanks! Let me know if there's anything else you'd like me to add - this feature (knowing the exact retweet id) is essential for studying spread of information

**Comment by bhalsey** [comment]
Thank you for incorporating our feedback.
Good news: the review team has approved your proposal!

Note that an approval does not guarantee an implementation; it means we agree in principle with the proposed changes and we will consider implementing. There are circumstances that may prevent implementation (for example, further privacy and security review, a change in roadmap or priorities, or a scheduled release of functionality that supersedes this proposal).

We’re very happy to see your contribution shaping the Twitter API, and we are grateful for the time and effort you put in authoring a proposal.

Thank you!

**Comment by igorbrigadir** [comment]
Awesome! Thanks!

**Pull request merged**
