### PR TITLE
feat: add relation info in user lookup object

### PR DESCRIPTION
**Pull request by redouane59**
I would like to enrich the `User` Object with `following` / `follower` information :)

### CODE REVIEW

**Comment by redouane59** [comment]
Ok :)

**Comment by redouane59** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. We ask that you agree to the [Twitter Developer Agreement and Policy](https://developer.twitter.com/en/developer-terms/agreement-and-policy) before we can accept your proposal. You can agree by posting a comment with the following text:
> 
> _**I have read and agree to the Twitter Developer Agreement and Policy**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read and agree to the Twitter Developer Agreement and Policy

**Comment by andypiper** [comment]
recheck

**Comment by redouane59** [comment]
Everything OK from my side @andypiper ?

**Comment by iamdaniele** [comment]
Hi @redouane59, I will be the review manager for this proposal. The team will evaluate the proposal and I will get back to you within two weeks.

**Comment by redouane59** [comment]
> Hi @redouane59, I will be the review manager for this proposal. The team will evaluate the proposal and I will get back to you within two weeks.

Great !

**Comment by iamdaniele** [comment]
Hi @redouane59, we are grateful for taking the time to create this proposal and to be part of open evolution of the Twitter API. We believe the functionality described is valuable and has a right to exist, and we will explore ways to add it to the platform. Sadly, after our review, we decided to reject this proposal as authored in its current form for the following reasons:

- The review teams believes that exposing relationship information in the user payload introduces a perspectival aspect to the user payload, which may make two otherwise identical payloads differ depending on who's requesting that payload. For example, Alice requesting Bob's payload may return the intended payload, but it's unclear what happens if Charlie requests Bob's payload, and what happens if they have a block relationship.
- The Alternatives considered section lists an increase of rate limits as a viable alternative. Rate limits exist to ensure and enforce Privacy and security, which is one of our [core principles](https://github.com/twitterdev/open-evolution/blob/main/principles.md). The review team believes there are other viable alternative solutions, for example, exposing an API route that would return the relationship between two or more users.
- It looks like this proposal mentions the v1.1 users/lookup endpoint; note that Open Evolution can only accept proposals related to the v2 Twitter API and above.


Like I said, just because we rejected this proposal, it doesn't mean that we'll never build this functionality. We will continue to explore alternatives to bring this functionality to the platform, in a way that's compatible with our foundational principles.

Just like in life, rejections are a fantastic tool for learning. We hope that this feedback was valuable; we encourage you to submit other proposals, and we look forward to reviewing them!

**Comment by redouane59** [comment]
Hey @iamdaniele , thanks for the detailed answer ! 
Obviously, if the rate limits to get all the followers / following users of an account were increased, it would be much easier.

**Pull request closed without merging**
